### ISSUE TITLE
Navbar 1 should be present on the registration page

### ISSUE THREAD

**Issue by ujjwalvkulkarni** [gcivil-nyu-org/team-4-inperson#191]
After Logging in with Google and redirecting to the Registration page, NavBar2 is currently displayed. NavBar1 should be displayed instead.

**Comment by ncolosso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/My-team-workspace-632bab919654ec00171644e8/issues/gcivil-nyu-org/team-4-inperson/191?planning-poker) with Zenhub @meoriordan @N17270182 @ujjwalvkulkarni @virenmparmar
