### ISSUE TITLE
Testing Party Issue - Google Sign-In with incomplete profile

### ISSUE THREAD

**Issue by sjeremycohen** [gcivil-nyu-org/team-4-inperson#209]
Environment Information:
**OS** Windows 11
**Browser** - Brave 1.45.127 Chromium 107.0.5304.110 (Extensions Disabled - Private Browser Window)
**Credential Used** - user5@test.com

**Error Encountered**
Incomplete 

**Reproduction Steps**

1. Navigate to Create Account
2. Click "Create account with Google"
3. Select correct NYU email account
4. Instead of finishing the account setup, navigate away
5. Go back to Create Account and click "Create Account with Google" again

**Error**
I am able to log in without entering any additional info. Here is my profile page.  Additionally, it is a strange discrepancy that I create the account with google and am expected to then sign in with a password. There should be (and by accident, already is) Google authenticated sign in.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/19637314/202807072-66d7755f-6671-481a-bda3-f03fc1078495.png">

**Comment by virenmparmar** [comment]
#191
