### ISSUE TITLE
Testing Party Issue: Review Text with No Limit

### ISSUE THREAD

**Issue by Pooja-Codes** [gcivil-nyu-org/team-4-inperson#210]
Testing Scenario: Writing a Review
OS Windows 11 || Browser Google Chrome
Credential - testuser1

There are no limits (word length and type of text)  to writing a review in Text Area.  

https://user-images.githubusercontent.com/87775823/202822721-5f87b6ab-725f-4eac-9254-c7ecfeea58ae.mp4

It is showing the below results if I input lengthy text and try to submit. Also, it is allowing me to try on submit with the wrong match of the course ID **&** _lengthy text._
<table>
 <tr>
    <td><img src="https://user-images.githubusercontent.com/87775823/202824114-2eeafbd8-beba-48a4-ba20-021d76de9ad0.jpg" alt="Site Can't Reached" width="600"/></td>
    <td><img src="https://user-images.githubusercontent.com/87775823/202823785-89eab544-f3b2-438c-bd83-ea6502e919b5.jpg" alt="Wait or Exit" width="600"/></td>
  </tr>
</table>

I have discussed this issue in class as well.

**Comment by virenmparmar** [comment]
#208 #207
