### ISSUE TITLE
Code User Registration View and URL

### ISSUE THREAD

**Issue by virenmparmar** [gcivil-nyu-org/team-4-inperson#39]

**Comment by ncolosso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/My-team-workspace-632bab919654ec00171644e8/issues/gcivil-nyu-org/team-4-inperson/39?planning-poker) with Zenhub @meoriordan @N17270182 @ujjwalvkulkarni @virenmparmar
