### ISSUE TITLE
Add Course/Professor Detail Page Links to Reviews

### ISSUE THREAD

**Issue by virenmparmar** [gcivil-nyu-org/team-4-inperson#62]
From course detail page, User can click on professor name for a review and be redirected to the professor detail page.

Similarly, from professor detail page, User can click on course name for a review and be redirected to the course detail page.

**Comment by ncolosso** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/My-team-workspace-632bab919654ec00171644e8/issues/gcivil-nyu-org/team-4-inperson/62?planning-poker) with Zenhub @meoriordan @N17270182 @ujjwalvkulkarni @virenmparmar
